"""Standard Codenames word list (400 words)."""

WORDS = [
    "Africa", "Agent", "Air", "Alien", "Alps", "Amazon", "Ambulance", "America",
    "Angel", "Antarctica", "Apple", "Arm", "Atlantis", "Australia", "Aztec",
    "Back", "Ball", "Band", "Bank", "Bar", "Bark", "Base", "Bat", "Battery",
    "Beach", "Bear", "Bed", "Bill", "Bite", "Block", "Board", "Bolt", "Bond",
    "Book", "Boom", "Boot", "Bottle", "Box", "Brain", "Branch", "Bridge", "Buck",
    "Buddy", "Bug", "Burn", "Button", "Cabin", "Canada", "Cap", "Capital", "Card",
    "Cast", "Cat", "Cell", "Chair", "Change", "Charge", "Check", "Chest", "China",
    "Chip", "Circle", "Class", "Cliff", "Club", "Coal", "Coast", "Code", "Cold",
    "Column", "Comic", "Cook", "Corner", "Cover", "Crack", "Crane", "Cross",
    "Crown", "Cycle", "Dam", "Date", "Day", "Diamond", "Die", "Dig", "Dinosaur",
    "Dog", "Draft", "Dragon", "Drop", "Duck", "Dust", "Eagle", "Egypt", "Engine",
    "Europe", "Eye", "Face", "Fall", "Fence", "Field", "File", "Film", "Fire",
    "Fish", "Flag", "Flat", "Flight", "Fly", "Foot", "Force", "Fork", "France",
    "Front", "Fruit", "Game", "Gate", "Ghost", "Giant", "Glacier", "Glass",
    "Glove", "Gold", "Grace", "Grass", "Green", "Ground", "Hand", "Head",
    "Heart", "Helicopter", "Hero", "High", "Hook", "Horn", "Horse", "Hospital",
    "Hotel", "Ice", "India", "Iron", "Jack", "Japan", "King", "Knight", "Lab",
    "Lead", "Leaf", "Lemon", "Letter", "Light", "Line", "Link", "Lion", "Lock",
    "Log", "London", "Marble", "March", "Match", "Mercury", "Mexico", "Mind",
    "Mine", "Mirror", "Model", "Moon", "Moscow", "Mount", "Mouse", "Mouth",
    "Nail", "Net", "Night", "Note", "Nurse", "Nut", "Oil", "Olive", "Orange",
    "Paper", "Paste", "Penguin", "Phoenix", "Piano", "Pilot", "Pin", "Pipe",
    "Pit", "Plane", "Plant", "Plate", "Plot", "Point", "Pole", "Police", "Pool",
    "Post", "Press", "Pumpkin", "Pupil", "Queen", "Reel", "Ring", "Rock",
    "Roller", "Root", "Rose", "Row", "Ruler", "Russia", "Satellite", "Saturn",
    "Scale", "Screen", "Seal", "Server", "Shadow", "Shark", "Shoe", "Shot",
    "Slip", "Slug", "Snow", "Soldier", "Space", "Spell", "Spider", "Spike",
    "Spirit", "Spring", "Spy", "Square", "Staff", "Stadium", "Star", "State",
    "Steam", "Strike", "Sub", "Sugar", "Table", "Tank", "Teacher", "Telescope",
    "Terminal", "Tick", "Time", "Toast", "Token", "Top", "Torch", "Tower",
    "Track", "Train", "Trick", "Trip", "Truck", "Turkey", "Undertaker",
    "Unicorn", "Union", "Vacuum", "Venus", "Vest", "Wake", "Wall", "Watch",
    "Well", "Whale", "Witch", "Wolf", "Worm", "Yard", "Zeus", "Zombie", "Zoo",
    "Anchor", "Arch", "Arrow", "Ash", "Avalanche", "Axe", "Bamboo", "Beacon",
    "Beam", "Bell", "Berry", "Blade", "Blank", "Blast", "Blossom", "Blur",
    "Bomb", "Bone", "Bounce", "Bow", "Brim", "Brooch", "Brook", "Brown",
    "Bruise", "Bubble", "Bulb", "Bullet", "Bun", "Burst", "Bush", "Cage",
    "Cake", "Canal", "Canyon", "Cape", "Capsule", "Cargo", "Cave", "Cedar",
    "Cement", "Chain", "Chamber", "Champion", "Channel", "Chapel", "Chart",
    "Chase", "Cherry", "Chill", "Chime", "Chip", "Claw", "Clay", "Clear",
    "Clip", "Clock", "Cloud", "Clue", "Coach", "Comet", "Compass", "Cone",
    "Copper", "Core", "Cord", "Cotton", "Couch", "Court", "Crest", "Crew",
    "Crop", "Cube", "Cup", "Dagger", "Dark", "Dart", "Dash", "Dawn", "Decay",
    "Deck", "Deep", "Deer", "Delta", "Den", "Depot", "Depth", "Desert",
    "Dew", "Dial", "Dice", "Disk", "Dome", "Door", "Dove", "Drill", "Drive",
    "Drum", "Dune", "Echo", "Edge", "Elm", "Ember", "Empire", "Era", "Escape",
    "Etch", "Exhaust", "Exile", "Fabric", "Fan", "Fang", "Farm", "Feather",
    "Ferry", "Flash", "Fleet", "Flesh", "Float", "Flow", "Flute", "Foam",
    "Fog", "Fold", "Forge", "Fort", "Fossil", "Fountain", "Fracture", "Frame",
    "Freeze", "Frost", "Fuse", "Gem", "Gene", "Glow", "Gorge", "Gust",
    "Harbor", "Haze", "Helm", "Hint", "Hollow", "Hull", "Husk", "Hymn",
    "Idol", "Ink", "Isle", "Ivy", "Jade", "Jar", "Jaw", "Jet", "Joint",
    "Jungle", "Keel", "Kelp", "Kettle", "Knot", "Lantern", "Lark", "Laser",
    "Lava", "Lens", "Lever", "Lily", "Lime", "Loom", "Loop", "Lure",
]
